declare module 'brace/mode/javascript'
declare module 'ace-builds/src-noconflict/mode-css.js'
declare module 'ace-builds/src-noconflict/mode-text.js'
declare module 'ace-builds/src-noconflict/mode-sql.js'
declare module 'ace-builds/src-noconflict/mode-scss.js'
declare module 'brace/mode/javascript'
declare module "ace-builds/src-noconflict/mode-sass.js";
declare module "ace-builds/src-noconflict/mode-php.js";
declare module "ace-builds/src-noconflict/mode-json.js";
declare module "ace-builds/src-noconflict/mode-java.js";
declare module "ace-builds/src-noconflict/mode-html.js";
declare module "ace-builds/src-noconflict/theme-ambiance.js";
declare module "ace-builds/src-noconflict/theme-gob.js";
declare module "brace/theme/chaos";
declare module "brace/theme/chrome";
declare module "brace/theme/clouds";
declare module "brace/theme/clouds_midnight";
declare module "brace/theme/cobalt";
declare module "brace/theme/crimson_editor";
declare module "brace/theme/dawn";
declare module "brace/theme/dracula";
declare module "brace/theme/dreamweaver";
declare module "brace/theme/eclipse";
declare module "brace/theme/github";
declare module "brace/theme/gruvbox";
declare module "brace/theme/idle_fingers";
declare module "brace/theme/iplastic";
declare module "brace/theme/katzenmilch";
declare module "brace/theme/tomorrow_night_blue";